const types = {
	FETCH_ALL_USER_LIST: 'FETCH_ALL_USER_LIST',
	FETCH_ALL_USER_LIST_ERR: 'FETCH_ALL_USER_LIST_ERR',
	FILTER_USER_LIST: 'FILTER_USER_LIST',
	FILTER_USER_LIST_ERR: 'FILTER_USER_LIST_ERR',
	FETCH_USER: 'FETCH_USER',
	FETCH_USER_ERR: 'FETCH_USER_ERR',
	DELETE_USER: 'DELETE_USER',
	DELETE_USER_ERR: 'DELETE_USER_ERR'
}

export default types;